// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGlqOkOELE-W8E-R5wDG1ZtAG0NET25Uo',
    appId: '1:1001128188991:web:5d0f0b87a62f3b4d7cac8a',
    messagingSenderId: '1001128188991',
    projectId: 'skillra-auth-test',
    authDomain: 'skillra-auth-test.firebaseapp.com',
    storageBucket: 'skillra-auth-test.firebasestorage.app',
    measurementId: 'G-5WHRVJJP72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpUhAujMEagqL11KpbftHJw9C4wvWMgBk',
    appId: '1:1001128188991:android:6175857acda69f047cac8a',
    messagingSenderId: '1001128188991',
    projectId: 'skillra-auth-test',
    storageBucket: 'skillra-auth-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZSAP8u_TP-OQOs8cG2CicQzNnL6bINQ',
    appId: '1:1001128188991:ios:e5c26202b76bd80e7cac8a',
    messagingSenderId: '1001128188991',
    projectId: 'skillra-auth-test',
    storageBucket: 'skillra-auth-test.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEmailLoginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVZSAP8u_TP-OQOs8cG2CicQzNnL6bINQ',
    appId: '1:1001128188991:ios:e5c26202b76bd80e7cac8a',
    messagingSenderId: '1001128188991',
    projectId: 'skillra-auth-test',
    storageBucket: 'skillra-auth-test.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEmailLoginTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGlqOkOELE-W8E-R5wDG1ZtAG0NET25Uo',
    appId: '1:1001128188991:web:7fd15e887bb6b4107cac8a',
    messagingSenderId: '1001128188991',
    projectId: 'skillra-auth-test',
    authDomain: 'skillra-auth-test.firebaseapp.com',
    storageBucket: 'skillra-auth-test.firebasestorage.app',
    measurementId: 'G-2PPLHVTMH5',
  );
}
